# Generated by Django 3.2.5 on 2022-12-06 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0002_alter_client_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybusiness',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_business', to=settings.AUTH_USER_MODEL),
        ),
    ]
