# Generated by Django 3.2.5 on 2022-12-07 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0004_alter_mybusiness_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybusiness',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
