# Generated by Django 3.2.5 on 2022-12-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0006_auto_20221209_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybusiness',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
