# Generated by Django 3.2.5 on 2023-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0007_mybusiness_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybusiness',
            name='settled_date',
            field=models.DateField(null=True),
        ),
    ]
