# Generated by Django 3.2.5 on 2023-01-16 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0009_rename_businesss_insuranceapplication_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=64)),
                ('notes', models.CharField(max_length=1024, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_insurance', to='mybusiness.mybusiness')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_businessinsurance', to=settings.AUTH_USER_MODEL)),
                ('insurance_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_insurance', to='mybusiness.insuranceapplication')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_insurance', to='mybusiness.insuranceplan')),
            ],
        ),
    ]
