# Generated by Django 3.2.5 on 2023-01-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0010_businessinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybusiness',
            name='settled_FYC',
            field=models.FloatField(null=True),
        ),
    ]
