# Generated by Django 3.2.5 on 2023-01-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0011_mybusiness_settled_fyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
    ]
