# Generated by Django 3.2.5 on 2023-01-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0013_clientaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
