# Generated by Django 3.2.5 on 2023-01-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0014_address_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='stree_address',
            new_name='street_address',
        ),
    ]
