# Generated by Django 3.2.5 on 2023-01-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0015_rename_stree_address_address_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_addresses', to='mybusiness.address'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_clients', to='mybusiness.client'),
        ),
    ]
