# Generated by Django 3.2.5 on 2023-01-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0017_auto_20230126_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='unit_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
