# Generated by Django 3.2.5 on 2023-02-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0018_address_unit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='client',
        ),
        migrations.AddField(
            model_name='phone',
            name='clients',
            field=models.ManyToManyField(to='mybusiness.Client'),
        ),
    ]
