# Generated by Django 3.2.5 on 2023-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0019_auto_20230201_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='client',
        ),
        migrations.AddField(
            model_name='email',
            name='clients',
            field=models.ManyToManyField(to='mybusiness.Client'),
        ),
    ]
