# Generated by Django 3.2.5 on 2023-02-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0020_auto_20230201_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='clients',
            field=models.ManyToManyField(related_name='phone_list', to='mybusiness.Client'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='mybusiness.phonetype'),
        ),
    ]
