# Generated by Django 3.2.5 on 2023-03-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0021_auto_20230201_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='insuranceapplication_medical',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='insuranceapplication_medical',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_applications', to='mybusiness.status'),
        ),
    ]
