# Generated by Django 3.2.5 on 2023-03-15 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0022_auto_20230309_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
