# Generated by Django 3.2.5 on 2023-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0023_alter_medical_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
