# Generated by Django 3.2.5 on 2023-03-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0024_alter_medical_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
    ]
