# Generated by Django 3.2.5 on 2023-03-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0026_collaboratorstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
