# Generated by Django 3.2.5 on 2023-04-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0027_collaboratorposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
    ]
