# Generated by Django 3.2.5 on 2023-04-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0028_remove_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
