# Generated by Django 3.2.5 on 2023-04-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0031_businesscomplianceentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business_ComplianceEntity',
        ),
    ]
