# Generated by Django 3.2.5 on 2023-04-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0032_delete_business_complianceentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessComplianceEntity',
        ),
    ]
