# Generated by Django 3.2.5 on 2023-04-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0033_delete_businesscomplianceentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessComplianceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1024, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesscomplianceentities', to='mybusiness.mybusiness')),
                ('compliance_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesscomplianceentities', to='mybusiness.complianceentity')),
            ],
        ),
    ]
