# Generated by Django 3.2.5 on 2023-04-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0034_businesscomplianceentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscomplianceentity',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
