# Generated by Django 3.2.5 on 2023-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0035_alter_businesscomplianceentity_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_document',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='business_document',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business_document',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
