# Generated by Django 3.2.5 on 2023-04-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0036_auto_20230419_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_medicals', to='mybusiness.mybusiness')),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_medicals', to='mybusiness.medical')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_medicals', to='mybusiness.status')),
            ],
        ),
        migrations.DeleteModel(
            name='InsuranceApplication_Medical',
        ),
    ]
