# Generated by Django 3.2.5 on 2023-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0038_insuranceapplication_applicant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapplication',
            name='applicant_address',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
