# Generated by Django 3.2.5 on 2023-05-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0041_alter_insuranceapplication_applicant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapplication',
            name='applicant_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_applications', to='mybusiness.phone'),
        ),
    ]
