# Generated by Django 3.2.5 on 2023-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0042_alter_insuranceapplication_applicant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='notes',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
