# Generated by Django 3.2.5 on 2023-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0043_alter_phone_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
