# Generated by Django 3.2.5 on 2023-05-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0044_alter_address_unit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_supervisor', to='mybusiness.mybusiness')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
