# Generated by Django 3.2.5 on 2023-05-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0045_businesssupervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybusiness',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
