# Generated by Django 3.2.5 on 2023-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0046_alter_mybusiness_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybusiness',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mybusiness',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
