# Generated by Django 3.2.5 on 2023-05-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0049_auto_20230522_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='business_user',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
