# Generated by Django 3.2.5 on 2023-07-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0051_insuranceapplication_insured_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceapplication',
            name='applicant_address',
        ),
    ]
