# Generated by Django 3.2.5 on 2023-07-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0052_remove_insuranceapplication_applicant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceapplication',
            name='applicant_phone',
        ),
    ]
