# Generated by Django 3.2.5 on 2023-07-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0054_auto_20230708_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybusiness',
            name='applicant_client_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mybusinesses', to='mybusiness.clientaddress'),
        ),
        migrations.AddField(
            model_name='mybusiness',
            name='applicant_client_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mybusinesses', to='mybusiness.phone'),
        ),
    ]
