# Generated by Django 3.2.5 on 2023-08-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0057_alter_mybusiness_applicant_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_user',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businessusers', to='mybusiness.businessuserrole'),
        ),
    ]
