# Generated by Django 3.2.5 on 2023-08-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0060_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='from_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification', to='mybusiness.mybusiness'),
            preserve_default=False,
        ),
    ]
