# Generated by Django 3.2.5 on 2023-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0063_auto_20230823_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='broadcast_group',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
