# Generated by Django 3.2.5 on 2023-09-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0065_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDeclined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_declined', to='mybusiness.mybusiness')),
            ],
        ),
    ]
