# Generated by Django 3.2.5 on 2023-05-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
