# Generated by Django 3.2.5 on 2023-06-01 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybusiness', '0050_auto_20230523_2330'),
        ('myapi', '0005_file_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='mybusiness.mybusiness'),
        ),
    ]
